# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Web

on:
  workflow_dispatch:

env:
  flutter_version: "2.10.5"
  my_secret: ${{secrets.commit_secret}}

jobs:
  build_web:
    runs-on: self-hosted
    steps:
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - run: flutter doctor -v
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - run: flutter clean
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --base-href="/skeleton_flutter/"
      
      - run: |
          cd build/web
          git init
          git config --global user.email robin_chang@owlting.com
          git config --global user.name robin_chang
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/robin00220/skeleton_flutter.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
